steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/semester2-412321/dhivakar100852462:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/semester2-412321/dhivakar100852462:latest']
options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
